name: "Ejercicio 4"
on:
  push:
    branches: [ "main" ]
jobs:
  test-multi-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm test
      - run: echo "Runner OS: ${{ runner.os }}"
      - name: Solo en Linux
        if: runner.os == 'Linux'
        run: echo "Este step solo aparece en Linux"
